matrix:
  include:
    - language: scala
      scala:
        - 2.12.8
      jdk: oraclejdk8
    - language: node_js
      node_js:
        - 10.15.0
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - cd web
      install:
        - yarn install

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  on:
#    branch: master